[settings]
activate_aggressive = true
paranoid = false

[settings.python]
compile = false

[tools]
"github:ogham/exa" = "latest"
"github:solidiquis/erdtree" = { version = "latest", exe = "erd" }
bat = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
gopass = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
neovim = "0.11.4"
nodejs = "lts"
perl = "latest"
python = ["3.10", "3.11", "3.12"]
restish = "latest"
ripgrep = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
golangci-lint = "latest"
jless = "latest"
jnv = "latest"
dyff = "latest"
