" Enable UTF8
scriptencoding UTF-8
set encoding=UTF-8

" General options
set number                      "Show line numbers
set ruler
set showmatch
set novisualbell                "Disable flash bell
set noerrorbells                "Disable bell
set smartcase
set ignorecase
set incsearch
set nocompatible
set undolevels=1000
set history=1000                "Store lots of :cmdline history
set backspace=indent,eol,start
set wrap
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set autoread                    "Reload files changed outside vim
set hidden
set shortmess+=F                " Disabled "filename" XXXL, XXXC
set noshowcmd                   " Disable display of last command
set noshowmode                  " Disable -- INSERT --
filetype on

" Search highlight
set hlsearch

" More natural split opening
set splitbelow
set splitright

" Easier split nav
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Indent stuff
set autoindent                  "Always set autoindenting on
set copyindent                  "Copy the previous indentation on autoindenting
set expandtab                   "Expand tabs by default (overloadable per file type)
set shiftround                  "Use multiple of shiftwidth when indenting with '<' and '>'
set shiftwidth=2                "Number of spaces to use for autoindenting
set smartindent
set smarttab                    "Insert tabs on the start of a line according to shiftwidth, not tabstop
set softtabstop=2               "When hitting <BS>, pretend like a tab is removed, even if spaces
set tabstop=2                   "Tabs are n spaces

" Enable folding
set foldmethod=indent
set foldnestmax=20
set nofoldenable
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za<CR>

" File format
set fileformat=unix

" Show Invisible
set list
set showbreak=↪\
set listchars=trail:•,tab:❯-,precedes:◀,extends:▶,nbsp:␣

" Copy/Paste OSX
set clipboard=unnamed

" Python settings
au BufNewFile,BufRead *.{py}
      \ set tabstop=4 |
      \ set softtabstop=4 |
      \ set shiftwidth=4 |
      \ set filetype=python |
      \ set autoindent |
      \ set expandtab |
      \ set textwidth=120

" Other Languages settings
au BufNewFile,BufRead *.js, *.html, *.css, *.yaml, *.json
      \ set tabstop=2 |
      \ set softtabstop=2 |
      \ set shiftwidth=2

" Set theme
syntax on
set termguicolors
if !has('gui_running') && &term =~ '\%(screen\|tmux\)'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
silent! colorscheme catpuccin_frappe
