# Prompt Symbol
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL="%F{white}❯%F{white}"
SPACESHIP_CHAR_SYMBOL_FAILURE="%F{red}❯%F{red}"

# Async
SPACESHIP_ASYNC_SHOW=false

# Dir
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_COLOR="blue"

# Git
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_GIT_SUFFIX=" "
SPACESHIP_GIT_STATUS_PREFIX=" "
SPACESHIP_GIT_STATUS_SUFFIX=""
SPACESHIP_GIT_STATUS_ADDED="%F{green}󰗡%F{green} "
SPACESHIP_GIT_STATUS_MODIFIED="%F{yellow}󰐾%F{yellow} "
SPACESHIP_GIT_STATUS_DELETED="%F{red}󰅚%F{red} "
SPACESHIP_GIT_STATUS_UNTRACKED="%F{white}󰝦%F{white} "
SPACESHIP_GIT_STATUS_STASHED="%F{blue}󰏦%F{blue} "
SPACESHIP_GIT_STATUS_BEHIND="%F{cyan}󰬧%F{cyan} "
SPACESHIP_GIT_STATUS_AHEAD="%F{cyan}󰬭%F{cyan} "
SPACESHIP_GIT_STATUS_DIVERGED="%F{magenta}󰮍%F{magenta} "
SPACESHIP_GIT_STATUS_RENAMED="%F{blue}󰿢%F{blue } "
SPACESHIP_GIT_STATUS_UNMERGED="%F{red}󱀗%F{red} "

# Execution time
SPACESHIP_EXEC_TIME_SHOW=false

# Package
SPACESHIP_PACKAGE_SYMBOL="󰏖 "

# Python
SPACESHIP_PYTHON_SYMBOL=" "
