BLUE="colour4"
RED="colour1"
GREEN="colour2"
YELLOW="colour3"
CYAN="colour6"

BLACK="colour16"
DARK_GREY="colour236"
GREY="colour239"
LIGHT_GREY="colour242"
DARK_WHITE="colour248"
WHITE="colour252"
XTRA_WHITE="colour254"

PRIMARY_1=$BLUE
PRIMARY_2=$CYAN
PRIMARY_3=$GREEN
PRIMARY_4=$YELLOW
PRIMARY_5=$RED

CTR_BG=$DARK_GREY

CTR_ST_TXT=$WHITE
CTR_ST_BG=$LIGHT_GREY
CTR_ST_ARROW_BG=$CTR_BG

CTR_ACT_ST_TXT=$DARK_GREY
CTR_ACT_ST_BG=$DARK_WHITE
CTR_ACT_ST_ARROW_BG=$CTR_BG

MSG_TXT=$WHITE
MSG_BG=$CTR_BG

LFT_PRI_TXT=$BLACK
LFT_PRI_ARROW_BG=$CTR_BG

RGT_SEC_TXT=$WHITE
RGT_SEC_BG=$LIGHT_GREY
RGT_SEC_ARROW_BG=$CTR_BG
RGT_SEC_ARROW_FG=$RGT_SEC_BG

RGT_PRI_TXT=$LFT_PRI_TXT
RGT_PRI_ARROW_BG=$RGT_SEC_BG

PANE_BDR_ACT=$YELLOW
PANE_BDR=$DARK_WHITE

source-file ~/.tmux.theme.conf
