# Change primary_color in function of session name
set -g @primary_color $PRIMARY_1

# How to use, start new session isolated by different socket
#
# TMUX_ENV=ssh
# tmux -L $TMUX_ENV new-session -s $TMUX_ENV -c $PWD
#
if-shell -F "#{==:#{session_name},remote}" \
  "set -g @primary_color $PRIMARY_2"

if-shell -F "#{==:#{session_name},dev}" \
  "set -g @primary_color $PRIMARY_3"

if-shell -F "#{==:#{session_name},preprod}" \
  "set -g @primary_color $PRIMARY_4"

if-shell -F "#{==:#{session_name},prod}" \
  "set -g @primary_color $PRIMARY_5"

# Set colors in function of session's name (reload tmux conf using tmux hooks)
set-hook -g session-renamed 'source-file -q "~/.tmux.conf"'
set-hook -g after-new-session 'source-file -q "~/.tmux.conf"'

# Messaging
set-option -g message-style "fg=$MSG_TXT,bg=$MSG_BG"

# Statusbar
set-option -g status-position top
set-option -g status-left-length 10
set-option -g status-right-length 100
set-option -g status-justify left
set-option -g status-style "fg=default,bg=$CTR_BG"
set-option -g status-left "#[fg=$LFT_PRI_TXT,bg=#{@primary_color},nobold]  #[fg=#{@primary_color},bg=$LFT_PRI_ARROW_BG,nobold]"
set-option -g status-right "#[fg=$RGT_SEC_ARROW_FG,bg=$RGT_SEC_ARROW_BG,nobold]#[fg=$RGT_SEC_TXT,bg=$RGT_SEC_BG,nobold]   #(whoami)    #{=|15|...:#{host}} #[fg=#{@primary_color},bg=$RGT_PRI_ARROW_BG,nobold]#[fg=$RGT_PRI_TXT,bg=#{@primary_color},nobold]   #{=|15|...:#{session_name}} "

# Panes
set-option -g pane-border-style "fg=$PANE_BDR,bg=default,dim"
set-option -g pane-active-border-style "fg=$PANE_BDR_ACT,bg=default"

# Windows
set-option -g window-style "bg=default"
set-option -g window-active-style "bg=default"
set-option -g window-status-separator ""

set-option -g window-status-current-format "#[fg=$CTR_ACT_ST_ARROW_BG,bg=$CTR_ACT_ST_BG,nobold]#[fg=$CTR_ACT_ST_TXT,bg=$CTR_ACT_ST_BG,nobold] #I  #W #{?#{||:#{window_zoomed_flag},#{||:#{window_bell_flag},#{window_activity_flag}}},#{?window_zoomed_flag,   ,}#{?window_bell_flag, 󰂞  ,}#{?window_activity_flag, 󰈈  ,},}#[fg=$CTR_ACT_ST_BG,bg=$CTR_ACT_ST_ARROW_BG,nobold]"
set-option -g window-status-format "#[fg=$CTR_ST_ARROW_BG,bg=$CTR_ST_BG,nobold]#[fg=$CTR_ST_TXT,bg=$CTR_ST_BG,nobold] #I  #W #{?#{||:#{window_zoomed_flag},#{||:#{window_bell_flag},#{window_activity_flag}}},#{?window_zoomed_flag,   ,}#{?window_bell_flag, 󰂞  ,}#{?window_activity_flag, 󰈈  ,},}#[fg=$CTR_ST_BG,bg=$CTR_ST_ARROW_BG,nobold]"

set-option -g status-position top
