# Zsh Home
export ZSH="${HOME}/.zsh"
export NVIM="${HOME}/.local/share/nvim"

# Settings
source "${ZSH}/config/settings.zsh"

# Keybindings
source "${ZSH}/config/bindings.zsh"

# Prompt
export SPACESHIP_CONFIG="${ZSH}/config/spaceship.zsh"
source "${ZSH}/plugins/spaceship/spaceship.zsh"

# Plugins
source "${ZSH}/config/plugins.zsh"

# Secrets
[[ ! -f "${ZSH}/config/secrets.zsh" ]] || source "${ZSH}/config/secrets.zsh"

# Completion
source "${ZSH}/config/completions.zsh"

# ASDF
export ASDF_DATA_DIR="${HOME}/.asdf"
export GOPATH="${HOME}/go"

# Path
path=(
  ${ASDF_DATA_DIR}/shims
  ${GOPATH}/bin
  ${NVIM}/mason/bin
  ${HOME}/bin
  ${HOME}/.local/bin
  $path
)
export PATH

# Aliases
source "${ZSH}/config/aliases.zsh"

# Functions
source "${ZSH}/config/functions.zsh"

# Work
[[ ! -f "${ZSH}/config/work.zsh" ]] || source "${ZSH}/config/work.zsh"
